export const resources = {
  pl: { translation: {
    common: { optional: "(opcjonalnie)", copy: "Kopiuj", copied: "Skopiowano!", select: "Wybierz…", description: "Opis", name: "Imię", cancel: "Anuluj", language: "Język", noAccount: "Konto nie jest wymagane." },
    landing: { title: "Route Community", subtitle: "Wgraj trasę GPX i udostępnij ją osobom, które znają okolicę." },
    upload: { file: "Plik GPX", routeName: "Nazwa trasy", description: "Opis", submit: "Wgraj trasę", uploading: "Wgrywanie…", emptyFile: "Wybierz niepusty plik GPX.", failed: "Nie udało się wgrać trasy." },
    ownerLink: { title: "Zapisz link do zarządzania", private: "Ten prywatny link daje Ci pełną kontrolę nad trasą. Zachowaj go w bezpiecznym miejscu i nie udostępniaj publicznie.", warning: "Route Community nie korzysta z kont, dlatego w razie utraty linku nie będziemy mogli przywrócić dostępu do zarządzania trasą.", label: "Link do zarządzania", copyAndContinue: "Skopiuj link do zarządzania i przejdź dalej", copiedOpening: "Skopiowano! Otwieranie trasy…", copyFailed: "Automatyczne kopiowanie zostało zablokowane. Zaznacz i skopiuj powyższy link ręcznie, a następnie potwierdź poniżej.", manualConfirm: "Link do zarządzania został przeze mnie skopiowany i bezpiecznie zapisany.", continue: "Przejdź do trasy" },
    route: { breadcrumb: "Zobacz trasę", viewRoute: "Zobacz trasę", suggestChanges: "Zaproponuj zmiany", openSuggestions: "Otwarta na sugestie", ownerMode: "Tryb właściciela", distance: "Dystans", elevationGain: "Przewyższenie", shared: "Udostępniono", more: "Więcej", moreSoon: "Więcej działań na trasie będzie dostępnych wkrótce", share: "Udostępnij trasę", details: "Szczegóły trasy", uploadedFile: "Wgrany plik", created: "Utworzono", start: "START", finish: "META", interactiveMap: "Interaktywna mapa trasy", distanceMarkers: "Znaczniki odległości:", off: "Wył.", fullscreen: "Mapa pełnoekranowa", exitFullscreen: "Wyjdź z pełnego ekranu", markerAria: "Znacznik trasy: {{distance}} km" },
    toolbar: { mode: "Tryb strony trasy", addNote: "Dodaj notatkę", flagSection: "Zgłoś odcinek", editRoute: "Edytuj trasę", suggesting: "Sugestia:", issue: "Problem", detour: "Objazd", note: "Notatka", positive: "Pozytywna opinia", futureStyles: "Przyszłe style znaczników społeczności" },
    elevation: { title: "Profil wysokości", totalGain: "↗ {{value}} m przewyższenia", showSuggestions: "Pokaż sugestie", unavailable: "Profil wysokości nie jest jeszcze dostępny dla tej trasy", explanation: "API udostępnia obecnie łączne przewyższenie, ale nie próbki wysokości dla poszczególnych punktów potrzebne do narysowania dokładnego wykresu.", noData: "Brak danych wysokościowych dla tej trasy.", gain: "↗ Podjazdy {{value}} m", loss: "↘ Zjazdy {{value}} m", minimum: "Min. {{value}} m", maximum: "Maks. {{value}} m", chartLabel: "Interaktywny profil wysokości trasy" },
    feedback: { shareTitle: "Udostępnij trasę i pozwól lokalnej społeczności ją ulepszyć!", shareText: "Zbieraj sugestie, omijaj złe drogi i odkrywaj ciekawe miejsca.", title: "Opinie o trasie", suggestions: "{{count}} sugestii", all: "Wszystkie", issues: "Problemy", detours: "Objazdy", notes: "Notatki", sortBy: "Sortuj", routeOrder: "Kolejność na trasie", add: "＋ Dodaj sugestię", noAccountName: "Konto nie jest wymagane. Wystarczy imię 🙂", filterSoon: "Filtrowanie „{{label}}” będzie dostępne wkrótce" },
    info: { recentActivity: "Ostatnia aktywność", historySoon: "Historia aktywności będzie dostępna wkrótce", viewAll: "Zobacz wszystko", download: "Pobierz", downloadSoon: "Pobieranie plików GPX nie jest jeszcze obsługiwane przez API", downloadGpx: "↓  Pobierz GPX", originalSoon: "Oryginalny plik nie jest jeszcze dostępny przez API", viewOriginal: "Zobacz oryginalny plik", unchanged: "Przyszłe zaakceptowane zmiany społeczności pojawią się tutaj. Obecny plik GPX nie został zmodyfikowany." },
    suggestion: { create: "Utwórz sugestię", intro: "Pomóż ulepszyć tę trasę dla kolejnych rowerzystów.", type: "Typ sugestii", chooseType: "Wybierz typ sugestii", chooseTypeHelp: "Wybierz jedną z opcji powyżej, aby rozpocząć.", reportIssue: "Zgłoś problem", reportIssueHelp: "Zaznacz niebezpieczny, zablokowany lub problematyczny odcinek.", suggestDetour: "Zaproponuj objazd", suggestDetourHelp: "Pokaż lepszy sposób ominięcia fragmentu trasy.", addNote: "Dodaj notatkę", addNoteHelp: "Dodaj przydatną lokalną informację do punktu na trasie.", chooseLocation: "Wybierz miejsce", chooseLocationHelp: "Kliknij w dowolnym miejscu trasy, aby dodać notatkę.", location: "Miejsce", categoryOptional: "Kategoria (opcjonalnie)", notePlaceholder: "Podziel się przydatną lokalną informacją…", review: "Sprawdź sugestię", chooseAnotherLocation: "Wybierz inne miejsce", selectIssue: "Wybierz problematyczny odcinek", selectIssueStart: "Kliknij trasę w miejscu, gdzie zaczyna się problem.", selectIssueEnd: "Teraz wybierz koniec problemu", selectIssueEndHelp: "Kliknij trasę ponownie, aby zaznaczyć koniec odcinka.", start: "Początek", affectedSection: "Odcinek objęty zgłoszeniem", length: "Długość {{value}}", describeIssue: "Opisz problem", category: "Kategoria", issuePlaceholder: "Co powinni wiedzieć inni rowerzyści?", anotherSection: "Wybierz inny odcinek", detourStart: "Wybierz początek objazdu", detourStartHelp: "Kliknij miejsce, w którym alternatywa ma opuścić obecną trasę.", drawAlternative: "Narysuj alternatywę", drawAlternativeHelp: "Klikaj mapę, aby dodawać punkty. Kliknij ponownie trasę, aby zakończyć objazd.", intermediatePoints_one: "{{count}} punkt pośredni", intermediatePoints_few: "{{count}} punkty pośrednie", intermediatePoints_many: "{{count}} punktów pośrednich", intermediatePoints_other: "{{count}} punktu pośredniego", undo: "Cofnij ostatni punkt", startOver: "Zacznij od nowa", describeDetour: "Opisz objazd", detourPlaceholder: "Dlaczego ta alternatywa jest lepsza?", reviewTitle: "Sprawdź swoją sugestię", reviewHelp: "Sprawdź szczegóły przed wysłaniem.", section: "Odcinek", originalDistance: "Pierwotny dystans", proposedDistance: "Przybliżony nowy dystans", difference: "Różnica", submit: "Wyślij sugestię", savingSoon: "Zapisywanie sugestii zostanie podłączone w kolejnym etapie wdrożenia.", backToEdit: "Wróć do edycji", yourName: "Twoje imię", tagsOptional: "Tagi (opcjonalnie)", original: "Pierwotnie", proposed: "Po zmianie", typeIssue: "Problem", typeDetour: "Objazd", typeNote: "Notatka" },
    options: { water: "Woda", food: "Jedzenie", surface: "Nawierzchnia", view: "Widok", services: "Usługi", other: "Inne", highTraffic: "Duży ruch", badSurface: "Zła nawierzchnia", roadClosed: "Droga zamknięta", construction: "Roboty drogowe", dangerous: "Niebezpiecznie", unpaved: "Droga nieutwardzona", betterSurface: "Lepsza nawierzchnia", lessTraffic: "Mniejszy ruch", safer: "Bezpieczniej", scenic: "Widokowo", avoidsClosure: "Omija zamknięcie" },
    activity: { detour: "{{name}} zaproponował objazd", note: "{{name}} dodała notatkę", issue: "{{name}} zgłosił problem", positive: "{{name}} dodała pozytywną opinię", hoursAgo: "2 godziny temu", dayAgo: "1 dzień temu", daysAgo: "2 dni temu" },
    health: { checking: "Sprawdzanie…", unavailable: "Niedostępne", unknown: "Nieznany", frontend: "Frontend", api: "API" },
    errors: { generic: "Coś poszło nie tak. Spróbuj ponownie." }
  } },
  en: { translation: {
    common: { optional: "(optional)", copy: "Copy", copied: "Copied!", select: "Select…", description: "Description", name: "Name", cancel: "Cancel", language: "Language", noAccount: "No account required." },
    landing: { title: "Route Community", subtitle: "Upload a GPX route and share it with people who know the area." },
    upload: { file: "GPX file", routeName: "Route name", description: "Description", submit: "Upload route", uploading: "Uploading…", emptyFile: "Choose a non-empty GPX file.", failed: "Upload failed." },
    ownerLink: { title: "Save your management link", private: "This private link gives you full control over this route. Keep it somewhere safe and do not share it publicly.", warning: "Route Community does not use accounts, so if you lose this link, we cannot recover access to route management.", label: "Management link", copyAndContinue: "Copy management link and continue", copiedOpening: "Copied! Opening route…", copyFailed: "Automatic copying was blocked. Select and copy the link above manually, then confirm below.", manualConfirm: "I have copied and safely saved the management link.", continue: "Continue to route" },
    route: { breadcrumb: "View route", viewRoute: "View route", suggestChanges: "Suggest changes", openSuggestions: "Open for suggestions", ownerMode: "Owner mode", distance: "Distance", elevationGain: "Elevation gain", shared: "Shared", more: "More", moreSoon: "More route actions are coming soon", share: "Share route", details: "Route details", uploadedFile: "Uploaded file", created: "Created", start: "START", finish: "FINISH", interactiveMap: "Interactive route map", distanceMarkers: "Distance markers:", off: "Off", fullscreen: "Fullscreen map", exitFullscreen: "Exit fullscreen", markerAria: "{{distance}} km route marker" },
    toolbar: { mode: "Route page mode", addNote: "Add note", flagSection: "Flag section", editRoute: "Edit route", suggesting: "Suggesting:", issue: "Issue", detour: "Detour", note: "Note", positive: "Positive", futureStyles: "Future community marker styles" },
    elevation: { title: "Elevation profile", totalGain: "↗ {{value}} m total gain", showSuggestions: "Show suggestions", unavailable: "Elevation profile is not available for this route yet", explanation: "The API currently provides total elevation gain, but not the per-point elevation samples needed to draw an accurate chart.", noData: "No elevation data available for this route.", gain: "↗ Gain {{value}} m", loss: "↘ Loss {{value}} m", minimum: "Min {{value}} m", maximum: "Max {{value}} m", chartLabel: "Interactive route elevation profile" },
    feedback: { shareTitle: "Share this route and let locals improve it!", shareText: "Get suggestions, avoid bad roads and find hidden gems.", title: "Route feedback", suggestions: "{{count}} suggestions", all: "All", issues: "Issues", detours: "Detours", notes: "Notes", sortBy: "Sort by", routeOrder: "Route order", add: "＋ Add your suggestion", noAccountName: "No account required. Just a name 🙂", filterSoon: "{{label}} filtering is coming soon" },
    info: { recentActivity: "Recent activity", historySoon: "Activity history is coming soon", viewAll: "View all", download: "Download", downloadSoon: "GPX downloads are not available in the API yet", downloadGpx: "↓  Download GPX", originalSoon: "Original file access is not available in the API yet", viewOriginal: "View original file", unchanged: "Future accepted community changes will be reflected here. The current GPX has not been modified." },
    suggestion: { create: "Create a suggestion", intro: "Help improve this route for the next rider.", type: "Suggestion type", chooseType: "Choose a suggestion type", chooseTypeHelp: "Select an option above to see how to begin.", reportIssue: "Report an issue", reportIssueHelp: "Mark a dangerous, blocked or problematic section.", suggestDetour: "Suggest a detour", suggestDetourHelp: "Show a better way around part of the route.", addNote: "Add a note", addNoteHelp: "Add useful local knowledge to a point on the route.", chooseLocation: "Choose a location", chooseLocationHelp: "Click anywhere on the route to attach your note.", location: "Location", categoryOptional: "Category (optional)", notePlaceholder: "Share useful local knowledge…", review: "Review suggestion", chooseAnotherLocation: "Choose another location", selectIssue: "Select the problematic section", selectIssueStart: "Click the route to mark where the problem starts.", selectIssueEnd: "Now select where the problem ends", selectIssueEndHelp: "Click the route again to mark the end of the affected section.", start: "Start", affectedSection: "Affected section", length: "Length {{value}}", describeIssue: "Describe the issue", category: "Category", issuePlaceholder: "What should other riders know?", anotherSection: "Select another section", detourStart: "Select where the detour starts", detourStartHelp: "Click the route where the alternative should leave the current route.", drawAlternative: "Draw the alternative", drawAlternativeHelp: "Click the map to add points. Click the route again to finish the detour.", intermediatePoints_one: "{{count}} intermediate point", intermediatePoints_few: "{{count}} intermediate points", intermediatePoints_many: "{{count}} intermediate points", intermediatePoints_other: "{{count}} intermediate points", undo: "Undo last point", startOver: "Start over", describeDetour: "Describe your detour", detourPlaceholder: "Why is this alternative better?", reviewTitle: "Review your suggestion", reviewHelp: "Check the details before submitting.", section: "Section", originalDistance: "Original distance", proposedDistance: "Approx. proposed distance", difference: "Difference", submit: "Submit suggestion", savingSoon: "Saving suggestions will be connected in the next implementation step.", backToEdit: "Back to edit", yourName: "Your name", tagsOptional: "Tags (optional)", original: "Original", proposed: "Approx. proposed", typeIssue: "Issue", typeDetour: "Detour", typeNote: "Note" },
    options: { water: "Water", food: "Food", surface: "Surface", view: "View", services: "Services", other: "Other", highTraffic: "High traffic", badSurface: "Bad surface", roadClosed: "Road closed", construction: "Construction", dangerous: "Dangerous", unpaved: "Unpaved", betterSurface: "Better surface", lessTraffic: "Less traffic", safer: "Safer", scenic: "Scenic", avoidsClosure: "Avoids closure" },
    activity: { detour: "{{name}} suggested a detour", note: "{{name}} added a note", issue: "{{name}} reported an issue", positive: "{{name}} added a positive note", hoursAgo: "2 hours ago", dayAgo: "1 day ago", daysAgo: "2 days ago" },
    health: { checking: "Checking…", unavailable: "Unavailable", unknown: "Unknown", frontend: "Frontend", api: "API" },
    errors: { generic: "Something went wrong. Please try again." }
  } }
} as const;
