package pl.routecommunity.api.route;

enum RouteActivityType {
    ROUTE_CREATED, VERSION_CREATED, OWNER_EDITED, METADATA_UPDATED, SUGGESTIONS_OPENED, SUGGESTIONS_CLOSED,
    SUGGESTION_CREATED, SUGGESTION_PUBLISHED, SUGGESTION_UNPUBLISHED, SUGGESTION_REJECTED, SUGGESTION_MERGED,
    COMMENT_CREATED, COMMENT_PUBLISHED, COMMENT_REJECTED, ROUTE_DELETED
}
