import assert from "node:assert/strict";import test from "node:test";
import { createEditorState,editorReducer,finalGeometry,affectedRoutedSegments,previewPointMove,type EditorState,type SegmentMode } from "../route-editor/model";
let n=0;const id=()=>`id-${++n}`;function add(state:EditorState,c:[number,number],mode:SegmentMode){return editorReducer(state,{type:"add",coordinate:c,mode,id:id(),segmentId:state.present.points.length?id():undefined})}
test("creates direct, routed and mixed segments in continuous order",()=>{let s=createEditorState();s=add(s,[1,1],"DIRECT");s=add(s,[2,2],"ROUTED");s=add(s,[3,3],"DIRECT");assert.deepEqual(s.present.segments.map(x=>x.mode),["ROUTED","DIRECT"]);assert.deepEqual(finalGeometry(s.present),[[1,1],[2,2],[3,3]])});
test("mode change is reversible with undo and redo",()=>{let s=createEditorState();s=add(add(s,[1,1],"DIRECT"),[2,2],"DIRECT");const segment=s.present.segments[0];s=editorReducer(s,{type:"mode",segmentId:segment.id,mode:"ROUTED"});assert.equal(s.present.segments[0].mode,"ROUTED");s=editorReducer(s,{type:"undo"});assert.equal(s.present.segments[0].mode,"DIRECT");s=editorReducer(s,{type:"redo"});assert.equal(s.present.segments[0].mode,"ROUTED")});
test("moving a point changes only adjacent segments",()=>{let s=createEditorState();for(let x=0;x<5;x++)s=add(s,[x,x],"ROUTED");const untouched=s.present.segments[3].geometry;s=editorReducer(s,{type:"move",pointId:s.present.points[2].id,coordinate:[2,4]});assert.deepEqual(s.present.segments[1].geometry.at(-1),[2,4]);assert.deepEqual(s.present.segments[2].geometry[0],[2,4]);assert.deepEqual(s.present.segments[3].geometry,untouched);assert.equal(affectedRoutedSegments(s.present,s.present.points[2].id).length,2)});
test("inserting and deleting control points preserves topology",()=>{let s=createEditorState();s=add(add(s,[0,0],"DIRECT"),[2,0],"DIRECT");const old=s.present.segments[0];s=editorReducer(s,{type:"insert",segmentId:old.id,coordinate:[1,0],id:"middle",leftId:"left",rightId:"right"});assert.equal(s.present.segments.length,2);s=editorReducer(s,{type:"remove",pointId:"middle",replacementId:"joined"});assert.deepEqual(finalGeometry(s.present),[[0,0],[2,0]])});
test("stale async routing result cannot overwrite newer result and failure keeps geometry",()=>{let s=createEditorState();s=add(add(s,[0,0],"ROUTED"),[2,0],"ROUTED");const segment=s.present.segments[0];s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:1});s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:2});s=editorReducer(s,{type:"routing-success",segmentId:segment.id,version:1,geometry:[[0,0],[9,9],[2,0]]});assert.deepEqual(s.present.segments[0].geometry,[[0,0],[2,0]]);s=editorReducer(s,{type:"routing-failure",segmentId:segment.id,version:2});assert.deepEqual(s.present.segments[0].geometry,[[0,0],[2,0]]);assert.equal(s.present.segments[0].routingStatus,"failed")});
test("routed geometry is anchored exactly to user control points",()=>{let s=createEditorState();s=add(add(s,[21.12345678,52.12345678],"ROUTED"),[21.2,52.2],"ROUTED");const segment=s.present.segments[0];s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:3});s=editorReducer(s,{type:"routing-success",segmentId:segment.id,version:3,geometry:[[21.123457,52.123457],[21.15,52.15],[21.2,52.2]]});assert.deepEqual(s.present.segments[0].geometry,[[21.12345678,52.12345678],[21.15,52.15],[21.2,52.2]])});

test("inserting into a direct segment snaps to it and preserves ordering",()=>{let s=createEditorState();s=add(add(s,[0,0],"DIRECT"),[4,0],"DIRECT");const original=s.present.segments[0];s=editorReducer(s,{type:"insert",segmentId:original.id,coordinate:[2,1],id:"inserted",leftId:"left",rightId:"right"});assert.deepEqual(s.present.points.map(p=>p.id),[s.present.points[0].id,"inserted",s.present.points[2].id]);assert.deepEqual(s.present.points[1].coordinate,[2,0]);assert.deepEqual(s.present.segments.map(x=>x.mode),["DIRECT","DIRECT"]);assert.deepEqual(finalGeometry(s.present),[[0,0],[2,0],[4,0]])});

test("inserting into routed geometry splits its existing shape without rerouting",()=>{let s=createEditorState();s=add(add(s,[0,0],"ROUTED"),[4,0],"ROUTED");const original=s.present.segments[0];s=editorReducer(s,{type:"routing-start",segmentId:original.id,version:1});s=editorReducer(s,{type:"routing-success",segmentId:original.id,version:1,geometry:[[0,0],[1,2],[3,2],[4,0]]});const before=finalGeometry(s.present);s=editorReducer(s,{type:"insert",segmentId:original.id,coordinate:[2,3],id:"inserted",leftId:"left",rightId:"right"});assert.deepEqual(s.present.segments.map(x=>x.mode),["ROUTED","ROUTED"]);assert.deepEqual(finalGeometry(s.present),[[0,0],[1,2],[2,2],[3,2],[4,0]]);assert.deepEqual(before.filter((_,i)=>i!==2),[[0,0],[1,2],[4,0]]);assert.equal(s.present.segments.every(x=>x.routingStatus==="idle"),true)});

test("insert undo and redo restore complete geometry",()=>{let s=createEditorState();s=add(add(s,[0,0],"DIRECT"),[2,0],"DIRECT");const original=s.present.segments[0];s=editorReducer(s,{type:"insert",segmentId:original.id,coordinate:[1,.5],id:"middle",leftId:"left",rightId:"right"});const inserted=structuredClone(s.present);s=editorReducer(s,{type:"undo"});assert.equal(s.present.points.length,2);assert.equal(s.present.segments[0].id,original.id);s=editorReducer(s,{type:"redo"});assert.deepEqual(s.present,inserted)});

test("one drag creates one history operation and undo/redo includes adjacent geometry",()=>{let s=createEditorState();s=add(s,[0,0],"DIRECT");s=add(s,[1,0],"DIRECT");s=add(s,[2,0],"DIRECT");const historyBefore=s.past.length,pointId=s.present.points[1].id;s=editorReducer(s,{type:"move",pointId,coordinate:[1,2]});const moved=structuredClone(s.present);assert.equal(s.past.length,historyBefore+1);assert.deepEqual(finalGeometry(s.present),[[0,0],[1,2],[2,0]]);s=editorReducer(s,{type:"undo"});assert.deepEqual(finalGeometry(s.present),[[0,0],[1,0],[2,0]]);s=editorReducer(s,{type:"redo"});assert.deepEqual(s.present,moved)});

test("drag preview handles routed and direct neighbours independently",()=>{let s=createEditorState();s=add(s,[0,0],"DIRECT");s=add(s,[1,0],"ROUTED");s=add(s,[2,0],"DIRECT");const left=s.present.segments[0],middle=s.present.points[1].id;s=editorReducer(s,{type:"routing-start",segmentId:left.id,version:1});s=editorReducer(s,{type:"routing-success",segmentId:left.id,version:1,geometry:[[0,0],[.5,.5],[1,0]]});const preview=previewPointMove(s.present,middle,[1,2]);assert.deepEqual(preview.segments[0].geometry,[[0,0],[.5,.5],[1,2]]);assert.deepEqual(preview.segments[1].geometry,[[1,2],[2,0]]);assert.deepEqual(affectedRoutedSegments(preview,middle).map(x=>x.id),[left.id])});

test("moving between two routed segments preserves their interiors and all unrelated segments",()=>{let s=createEditorState();for(let x=0;x<5;x++)s=add(s,[x,0],"ROUTED");for(const [index,segment] of s.present.segments.entries()){s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:index+1});s=editorReducer(s,{type:"routing-success",segmentId:segment.id,version:index+1,geometry:[[index,0],[index+.5,1],[index+1,0]]})}const untouchedLeft=structuredClone(s.present.segments[0]),untouchedRight=structuredClone(s.present.segments[3]),pointId=s.present.points[2].id;s=editorReducer(s,{type:"move",pointId,coordinate:[2,3]});assert.deepEqual(s.present.segments[0],untouchedLeft);assert.deepEqual(s.present.segments[3],untouchedRight);assert.deepEqual(s.present.segments[1].geometry,[[1,0],[1.5,1],[2,3]]);assert.deepEqual(s.present.segments[2].geometry,[[2,3],[2.5,1],[3,0]])});

test("routing failure after a drag keeps moved point, preview shape, and unrelated geometry",()=>{let s=createEditorState();for(let x=0;x<4;x++)s=add(s,[x,0],"ROUTED");const unrelated=structuredClone(s.present.segments[2]),pointId=s.present.points[1].id;s=editorReducer(s,{type:"move",pointId,coordinate:[1,2]});const affected=s.present.segments[0];s=editorReducer(s,{type:"routing-start",segmentId:affected.id,version:20});s=editorReducer(s,{type:"routing-failure",segmentId:affected.id,version:20});assert.deepEqual(s.present.points[1].coordinate,[1,2]);assert.deepEqual(s.present.segments[0].geometry.at(-1),[1,2]);assert.deepEqual(s.present.segments[2],unrelated);assert.equal(s.present.segments[0].routingStatus,"failed")});

test("deleting a middle point joins only its neighbours and routed wins mixed mode",()=>{let s=createEditorState();s=add(s,[0,0],"DIRECT");s=add(s,[1,0],"DIRECT");s=add(s,[2,0],"ROUTED");s=add(s,[3,0],"DIRECT");const untouched=s.present.segments[2],pointId=s.present.points[1].id;s=editorReducer(s,{type:"remove",pointId,replacementId:"joined"});assert.deepEqual(s.present.points.map(p=>p.coordinate),[[0,0],[2,0],[3,0]]);assert.equal(s.present.segments[0].id,"joined");assert.equal(s.present.segments[0].mode,"ROUTED");assert.deepEqual(s.present.segments[1],untouched);s=editorReducer(s,{type:"undo"});assert.equal(s.present.points.length,4);s=editorReducer(s,{type:"redo"});assert.deepEqual(finalGeometry(s.present),[[0,0],[2,0],[3,0]])});

test("final geometry remains continuous after insert move and delete",()=>{let s=createEditorState();s=add(s,[0,0],"DIRECT");s=add(s,[2,0],"DIRECT");s=add(s,[4,0],"DIRECT");s=editorReducer(s,{type:"insert",segmentId:s.present.segments[0].id,coordinate:[1,1],id:"new",leftId:"left",rightId:"right"});s=editorReducer(s,{type:"move",pointId:"new",coordinate:[1,2]});s=editorReducer(s,{type:"remove",pointId:s.present.points[2].id,replacementId:"joined"});assert.deepEqual(finalGeometry(s.present),[[0,0],[1,2],[4,0]]);for(let i=1;i<s.present.segments.length;i++)assert.deepEqual(s.present.segments[i-1].geometry.at(-1),s.present.segments[i].geometry[0])});
