import assert from "node:assert/strict";import test from "node:test";
import { createEditorState,editorReducer,finalGeometry,affectedRoutedSegments,type EditorState,type SegmentMode } from "../route-editor/model";
let n=0;const id=()=>`id-${++n}`;function add(state:EditorState,c:[number,number],mode:SegmentMode){return editorReducer(state,{type:"add",coordinate:c,mode,id:id(),segmentId:state.present.points.length?id():undefined})}
test("creates direct, routed and mixed segments in continuous order",()=>{let s=createEditorState();s=add(s,[1,1],"DIRECT");s=add(s,[2,2],"ROUTED");s=add(s,[3,3],"DIRECT");assert.deepEqual(s.present.segments.map(x=>x.mode),["ROUTED","DIRECT"]);assert.deepEqual(finalGeometry(s.present),[[1,1],[2,2],[3,3]])});
test("mode change is reversible with undo and redo",()=>{let s=createEditorState();s=add(add(s,[1,1],"DIRECT"),[2,2],"DIRECT");const segment=s.present.segments[0];s=editorReducer(s,{type:"mode",segmentId:segment.id,mode:"ROUTED"});assert.equal(s.present.segments[0].mode,"ROUTED");s=editorReducer(s,{type:"undo"});assert.equal(s.present.segments[0].mode,"DIRECT");s=editorReducer(s,{type:"redo"});assert.equal(s.present.segments[0].mode,"ROUTED")});
test("moving a point changes only adjacent segments",()=>{let s=createEditorState();for(let x=0;x<5;x++)s=add(s,[x,x],"ROUTED");const untouched=s.present.segments[3].geometry;s=editorReducer(s,{type:"move",pointId:s.present.points[2].id,coordinate:[2,4]});assert.deepEqual(s.present.segments[1].geometry.at(-1),[2,4]);assert.deepEqual(s.present.segments[2].geometry[0],[2,4]);assert.deepEqual(s.present.segments[3].geometry,untouched);assert.equal(affectedRoutedSegments(s.present,s.present.points[2].id).length,2)});
test("inserting and deleting control points preserves topology",()=>{let s=createEditorState();s=add(add(s,[0,0],"DIRECT"),[2,0],"DIRECT");const old=s.present.segments[0];s=editorReducer(s,{type:"insert",segmentId:old.id,coordinate:[1,0],id:"middle",leftId:"left",rightId:"right"});assert.equal(s.present.segments.length,2);s=editorReducer(s,{type:"remove",pointId:"middle",replacementId:"joined"});assert.deepEqual(finalGeometry(s.present),[[0,0],[2,0]])});
test("stale async routing result cannot overwrite newer result and failure keeps geometry",()=>{let s=createEditorState();s=add(add(s,[0,0],"ROUTED"),[2,0],"ROUTED");const segment=s.present.segments[0];s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:1});s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:2});s=editorReducer(s,{type:"routing-success",segmentId:segment.id,version:1,geometry:[[0,0],[9,9],[2,0]]});assert.deepEqual(s.present.segments[0].geometry,[[0,0],[2,0]]);s=editorReducer(s,{type:"routing-failure",segmentId:segment.id,version:2});assert.deepEqual(s.present.segments[0].geometry,[[0,0],[2,0]]);assert.equal(s.present.segments[0].routingStatus,"failed")});
test("routed geometry is anchored exactly to user control points",()=>{let s=createEditorState();s=add(add(s,[21.12345678,52.12345678],"ROUTED"),[21.2,52.2],"ROUTED");const segment=s.present.segments[0];s=editorReducer(s,{type:"routing-start",segmentId:segment.id,version:3});s=editorReducer(s,{type:"routing-success",segmentId:segment.id,version:3,geometry:[[21.123457,52.123457],[21.15,52.15],[21.2,52.2]]});assert.deepEqual(s.present.segments[0].geometry,[[21.12345678,52.12345678],[21.15,52.15],[21.2,52.2]])});
